//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace WebRole1.Ptt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SorguSoap11Binding", Namespace="http://takip.ptt.gov.tr")]
    public partial class Sorgu : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback gonderiSorguOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sorgu() {
            this.Url = global::WebRole1.Properties.Settings.Default.WebRole1_Ptt_Sorgu;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event gonderiSorguCompletedEventHandler gonderiSorguCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:gonderiSorgu", RequestNamespace="http://takip.ptt.gov.tr", ResponseNamespace="http://takip.ptt.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public OutputTum gonderiSorgu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Input input) {
            object[] results = this.Invoke("gonderiSorgu", new object[] {
                        input});
            return ((OutputTum)(results[0]));
        }
        
        /// <remarks/>
        public void gonderiSorguAsync(Input input) {
            this.gonderiSorguAsync(input, null);
        }
        
        /// <remarks/>
        public void gonderiSorguAsync(Input input, object userState) {
            if ((this.gonderiSorguOperationCompleted == null)) {
                this.gonderiSorguOperationCompleted = new System.Threading.SendOrPostCallback(this.OngonderiSorguOperationCompleted);
            }
            this.InvokeAsync("gonderiSorgu", new object[] {
                        input}, this.gonderiSorguOperationCompleted, userState);
        }
        
        private void OngonderiSorguOperationCompleted(object arg) {
            if ((this.gonderiSorguCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gonderiSorguCompleted(this, new gonderiSorguCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://takip.ptt.gov.tr/xsd")]
    public partial class Input {
        
        private string barkodField;
        
        private string kullaniciField;
        
        private string sifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                this.kullaniciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://takip.ptt.gov.tr/xsd")]
    public partial class OutputDongu {
        
        private string iMERKField;
        
        private string iSLEMField;
        
        private string iTARIHField;
        
        private System.Nullable<int> siraNoField;
        
        private bool siraNoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IMERK {
            get {
                return this.iMERKField;
            }
            set {
                this.iMERKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ISLEM {
            get {
                return this.iSLEMField;
            }
            set {
                this.iSLEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ITARIH {
            get {
                return this.iTARIHField;
            }
            set {
                this.iTARIHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> siraNo {
            get {
                return this.siraNoField;
            }
            set {
                this.siraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siraNoSpecified {
            get {
                return this.siraNoFieldSpecified;
            }
            set {
                this.siraNoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://takip.ptt.gov.tr/xsd")]
    public partial class OutputTum {
        
        private string aLICIField;
        
        private string bARNOField;
        
        private string dEGKONUCRField;
        
        private string eKHIZField;
        
        private string gONDERENField;
        
        private string gONUCRField;
        
        private string grField;
        
        private string iMERKField;
        
        private string iTARIHField;
        
        private string oDSARUCRField;
        
        private string tESALANField;
        
        private string vMERKField;
        
        private OutputDongu[] donguField;
        
        private string sonucAciklamaField;
        
        private System.Nullable<int> sonucKoduField;
        
        private bool sonucKoduFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ALICI {
            get {
                return this.aLICIField;
            }
            set {
                this.aLICIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BARNO {
            get {
                return this.bARNOField;
            }
            set {
                this.bARNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DEGKONUCR {
            get {
                return this.dEGKONUCRField;
            }
            set {
                this.dEGKONUCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EKHIZ {
            get {
                return this.eKHIZField;
            }
            set {
                this.eKHIZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GONDEREN {
            get {
                return this.gONDERENField;
            }
            set {
                this.gONDERENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GONUCR {
            get {
                return this.gONUCRField;
            }
            set {
                this.gONUCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GR {
            get {
                return this.grField;
            }
            set {
                this.grField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IMERK {
            get {
                return this.iMERKField;
            }
            set {
                this.iMERKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ITARIH {
            get {
                return this.iTARIHField;
            }
            set {
                this.iTARIHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ODSARUCR {
            get {
                return this.oDSARUCRField;
            }
            set {
                this.oDSARUCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TESALAN {
            get {
                return this.tESALANField;
            }
            set {
                this.tESALANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VMERK {
            get {
                return this.vMERKField;
            }
            set {
                this.vMERKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dongu", IsNullable=true)]
        public OutputDongu[] dongu {
            get {
                return this.donguField;
            }
            set {
                this.donguField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sonucAciklama {
            get {
                return this.sonucAciklamaField;
            }
            set {
                this.sonucAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sonucKoduSpecified {
            get {
                return this.sonucKoduFieldSpecified;
            }
            set {
                this.sonucKoduFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void gonderiSorguCompletedEventHandler(object sender, gonderiSorguCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gonderiSorguCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gonderiSorguCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputTum Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputTum)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591