//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Spk {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.spk.gov.tr/webservices/", ConfigurationName="Spk.MFundsServiceSoap")]
    public interface MFundsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsCodeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFundsCodeName(char cType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsCodeName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFundsCodeNameAsync(char cType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetYOCodeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetYOCodeName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetYOCodeName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetYOCodeNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetFundInfos(string strFonKod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundInfos", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetFundInfosAsync(string strFonKod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsSummaryInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFundsSummaryInfos(System.DateTime theDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsSummaryInfos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFundsSummaryInfosAsync(System.DateTime theDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundPortfolioValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFundPortfolioValues(string strTakasCode, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundPortfolioValues", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFundPortfolioValuesAsync(string strTakasCode, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsPortfolioValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFundsPortfolioValues(string strTakasCodeBegin, string strTakasCodeEnd, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsPortfolioValues", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFundsPortfolioValuesAsync(string strTakasCodeBegin, string strTakasCodeEnd, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundPortfolioValuesMonthly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFundPortfolioValuesMonthly(string strFonKod, int theYear, int theMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundPortfolioValuesMonthly", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFundPortfolioValuesMonthlyAsync(string strFonKod, int theYear, int theMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsPortfolioValuesDaily", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFundsPortfolioValuesDaily(System.DateTime theDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetFundsPortfolioValuesDaily", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFundsPortfolioValuesDailyAsync(System.DateTime theDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetYOPortfolioValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetYOPortfolioValues(string strCompanyCodeBegin, string strCompanyCodeEnd, System.DateTime dateBegin, System.DateTime dateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.spk.gov.tr/webservices/GetYOPortfolioValues", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetYOPortfolioValuesAsync(string strCompanyCodeBegin, string strCompanyCodeEnd, System.DateTime dateBegin, System.DateTime dateEnd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MFundsServiceSoapChannel : WebRole1.Spk.MFundsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MFundsServiceSoapClient : System.ServiceModel.ClientBase<WebRole1.Spk.MFundsServiceSoap>, WebRole1.Spk.MFundsServiceSoap {
        
        public MFundsServiceSoapClient() {
        }
        
        public MFundsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MFundsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MFundsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MFundsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetFundsCodeName(char cType) {
            return base.Channel.GetFundsCodeName(cType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFundsCodeNameAsync(char cType) {
            return base.Channel.GetFundsCodeNameAsync(cType);
        }
        
        public System.Data.DataSet GetYOCodeName() {
            return base.Channel.GetYOCodeName();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetYOCodeNameAsync() {
            return base.Channel.GetYOCodeNameAsync();
        }
        
        public string[] GetFundInfos(string strFonKod) {
            return base.Channel.GetFundInfos(strFonKod);
        }
        
        public System.Threading.Tasks.Task<string[]> GetFundInfosAsync(string strFonKod) {
            return base.Channel.GetFundInfosAsync(strFonKod);
        }
        
        public System.Data.DataSet GetFundsSummaryInfos(System.DateTime theDate) {
            return base.Channel.GetFundsSummaryInfos(theDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFundsSummaryInfosAsync(System.DateTime theDate) {
            return base.Channel.GetFundsSummaryInfosAsync(theDate);
        }
        
        public System.Data.DataSet GetFundPortfolioValues(string strTakasCode, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd) {
            return base.Channel.GetFundPortfolioValues(strTakasCode, strCompanyType, dateBegin, dateEnd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFundPortfolioValuesAsync(string strTakasCode, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd) {
            return base.Channel.GetFundPortfolioValuesAsync(strTakasCode, strCompanyType, dateBegin, dateEnd);
        }
        
        public System.Data.DataSet GetFundsPortfolioValues(string strTakasCodeBegin, string strTakasCodeEnd, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd) {
            return base.Channel.GetFundsPortfolioValues(strTakasCodeBegin, strTakasCodeEnd, strCompanyType, dateBegin, dateEnd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFundsPortfolioValuesAsync(string strTakasCodeBegin, string strTakasCodeEnd, string strCompanyType, System.DateTime dateBegin, System.DateTime dateEnd) {
            return base.Channel.GetFundsPortfolioValuesAsync(strTakasCodeBegin, strTakasCodeEnd, strCompanyType, dateBegin, dateEnd);
        }
        
        public System.Data.DataSet GetFundPortfolioValuesMonthly(string strFonKod, int theYear, int theMonth) {
            return base.Channel.GetFundPortfolioValuesMonthly(strFonKod, theYear, theMonth);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFundPortfolioValuesMonthlyAsync(string strFonKod, int theYear, int theMonth) {
            return base.Channel.GetFundPortfolioValuesMonthlyAsync(strFonKod, theYear, theMonth);
        }
        
        public System.Data.DataSet GetFundsPortfolioValuesDaily(System.DateTime theDate) {
            return base.Channel.GetFundsPortfolioValuesDaily(theDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFundsPortfolioValuesDailyAsync(System.DateTime theDate) {
            return base.Channel.GetFundsPortfolioValuesDailyAsync(theDate);
        }
        
        public System.Data.DataSet GetYOPortfolioValues(string strCompanyCodeBegin, string strCompanyCodeEnd, System.DateTime dateBegin, System.DateTime dateEnd) {
            return base.Channel.GetYOPortfolioValues(strCompanyCodeBegin, strCompanyCodeEnd, dateBegin, dateEnd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetYOPortfolioValuesAsync(string strCompanyCodeBegin, string strCompanyCodeEnd, System.DateTime dateBegin, System.DateTime dateEnd) {
            return base.Channel.GetYOPortfolioValuesAsync(strCompanyCodeBegin, strCompanyCodeEnd, dateBegin, dateEnd);
        }
    }
}
